import { Router } from 'express';
import authRoutes from './authRoutes';
import userRoutes from './userRoutes';
import roleRoutes from './roleRoutes';
import profileRoutes from './profileRoutes';
import auditRoutes from './auditRoutes';
import crmRoutes from './crmRoutes';
import projectRoutes from './projectRoutes';
import taskRoutes from './taskRoutes';
import teamRoutes from './teamRoutes';
import notificationRoutes from './notificationRoutes';
import dashboardRoutes from './dashboardRoutes';
import financeRoutes from './financeRoutes';
import dmsRoutes from './dmsRoutes';
import seoRoutes from './seoRoutes';
import aiRoutes from './aiRoutes';
import reportsRoutes from './reportsRoutes';
import calendarRoutes from './calendarRoutes';
import automationRoutes from './automationRoutes';
import saasRoutes from './saasRoutes';
import healthRoutes from './healthRoutes';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/system', roleRoutes);
router.use('/profile', profileRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/crm', crmRoutes);
router.use('/projects', projectRoutes);
router.use('/tasks', taskRoutes);
router.use('/team', teamRoutes);
router.use('/notifications', notificationRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/finance', financeRoutes);
router.use('/dms', dmsRoutes);
router.use('/seo', seoRoutes);
router.use('/ai', aiRoutes);
router.use('/reports', reportsRoutes);
router.use('/calendar', calendarRoutes);
router.use('/automation', automationRoutes);
router.use('/saas', saasRoutes);

export default router;
