export const PERMISSIONS = {
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_VIEW: 'users.view',
  PROJECTS_CREATE: 'projects.create',
  PROJECTS_UPDATE: 'projects.update',
  PROJECTS_DELETE: 'projects.delete',
  TASKS_CREATE: 'tasks.create',
  TASKS_UPDATE: 'tasks.update',
  FINANCE_MANAGE: 'finance.manage',
  CRM_MANAGE: 'crm.manage',
  SEO_MANAGE: 'seo.manage',
  REPORTS_VIEW: 'reports.view',
  SETTINGS_MANAGE: 'settings.manage',
} as const;

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  'Super Admin': Object.values(PERMISSIONS),
  'Admin': [
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.CRM_MANAGE,
    PERMISSIONS.SEO_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  'Project Manager': [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.PROJECTS_CREATE,
    PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  'Business Analyst': [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.PROJECTS_UPDATE,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  'Developer': [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.TASKS_UPDATE,
  ],
  'QA/Tester': [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  'SEO Executive': [
    PERMISSIONS.SEO_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  'Finance': [
    PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  'Client': [
    PERMISSIONS.REPORTS_VIEW,
  ],
};
